### ISSUE TITLE
Broken ARM 32-bit

### ISSUE THREAD

**Issue by koron393** [crdroidandroid/android_bionic#6]
After commit [0006665831b94a938c7c0f5f35b32333cae58c51](https://github.com/crdroidandroid/android_bionic/commit/0006665831b94a938c7c0f5f35b32333cae58c51)

my old 32-bit only device does not boot up.

When I revert
https://github.com/crdroidandroid/android_bionic/commit/0006665831b94a938c7c0f5f35b32333cae58c51
https://github.com/crdroidandroid/android_bionic/commit/571d0a6e04dbc2da81f3bf3a363f5a544011a0a2
https://github.com/crdroidandroid/android_bionic/commit/d929db6f7e9e6b4b83df425d06196e745d7d0274
https://github.com/crdroidandroid/android_bionic/commit/e02f4026cd3ff0c6b9bd3cfb771fbd15018b3ff7

device boots up.

**Comment by neobuddy89** [comment]
Removed conflicting and relevant commits.
